services:
  - type: web
    name: gitboost-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi
    envVars:
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
